config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'

  get 'static_pages/about'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
	resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :remember_token

	validates :username, :email, :password, presence: true 
	has_secure_password

	def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

	def User.new_token
		SecureRandom.urlsafe_base64
	end

	def remember
		self.remember_token=User.new_token
		update_attribute(:remember_digest, User.digest(:remember_token))
	end

	 def forget
    update_attribute(:remember_digest, nil)
  end

def authenticated?(remember_token)
	return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
   	log_in user
     params[:session][:remember_me] == '1' ? remember(user) : forget(user)
    redirect_to user
    else	
    flash[:danger] = 'Invalid email/password combination'
  	render 'new'
  	end
   end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	

	def new
	@user=User.new
	end

	def index
		@users=User.all
	end

	def show
		@user=User.find(params[:id])
	end

	def create
		@user=User.new(user_params)

		if @user.save
			redirect_to new_user_path
		end
	end

	
	def user_params
		params.require(:user).permit(:username, :email, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
   if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def logged_in?
  	!@current_user.nil?
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Brian App </title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "sample app", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "About",   '#' %></li>
            <li><%= link_to "Log in", login_path %></li>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Nagoozy Sample</h1>

  <h2>
    This is the home page for the
    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application
  </h2>

  <%= link_to "Sign up now!", new_user_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>

app/views/users/index.html.erb
<h1>All Articles</h1>

<ul id="users">
  <% @users.each do |user| %>
    <li>
      <%=link_to user.username, user_path(user) %>
    </li>
  <% end %>

</ul>

app/views/users/new.html.erb
<h1> Sign Up </h1>

<%= form_for @user do |f| %>
<%=f.label :username %>
<%=f.text_field :username %> <br>
<%=f.label :email %>
<%=f.text_field :email %> <br>
<%=f.label :password %>
<%=f.password_field :password %> <br>
<%=f.submit "Create" %>
<% end %>

app/views/users/show.html.erb
<h1><%=@user.username%></h1>
<h1><%=@user.email%></h1>